### ISSUE TITLE
path to (default) avatar icon in upper right corner is wrong

### ISSUE THREAD

**Issue by mediaessenz** [FriendsOfTYPO3/frontend_editing#217]
Console shows:
GET http://typo3/sysext/core/Resources/Public/Icons/T3Icons/avatar/avatar-default.svg net::ERR_NAME_NOT_RESOLVED

**Comment by MattiasNilsson** [comment]
@mediaessenz I can´t reproduce this. Can you provide more specifics like:

* Which TYPO3 version
* Which version of frontend_editing are you using
* PHP version

**Comment by webian** [comment]
@mediaessenz it could be useful also to know:
- operating system
- web server (apache? ngix?)
- web server configuration (virtual host?)
- how is your TYPO3 installed (composer; symlinked; etc)

because I suspect that it's problem in path resolving depending on the platform where your installation is executed.

**Comment by mediaessenz** [comment]
The problem seem to be already solved in the latest version.
