### ISSUE TITLE
Risk of losing changes (part 2)

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#235]
Related to #185

Other cases where it's possible to loose changes:
1. The editor drops a new content element after an edit. The new CE modal pops up and when closed it refresh the page loosing the eventual changes not saved before the creation of the new CE.
2. The editor hides a modified CE. The page is reloaded and changes lost.

**Comment by webian** [comment]
3. When an existing CE is dragged & dropped, the page refresh and changes are lost.

**Comment by pxamike** [comment]
@webian I have tested this with 1.6.1 (actually 07eb4828) and in the case of these page reloads, the changes are not lost. They disappear from the frontend as the original content is reloaded, but the changes are reflected in the Save All button (it turns orange and show number of changes) in the top right corner and after pressing it, the changes are applied to the page. If you try to leave the page, you are also queried about saving or losing the changes.

It's possible it was a different outcome when this bug was filed though.

So now it's a question if it's possible to show these changes when page is reloaded (caused by editing).

**Comment by mabolek** [comment]
@pxamike IMO the script should open a modal requesting to save existing changes. Otherwise the page will reload without the changes, and the user might try to do them again.

**Comment by mabolek** [comment]
@pxamike Or how about:

1. Reload the page
2. Dynamically apply old changes
