### ISSUE TITLE
Can't navigate in Typo3 backend after using modal editing

### ISSUE THREAD

**Issue by kevinandrewsde** [FriendsOfTYPO3/frontend_editing#390]
I cant seem to be able to use the navigation built in to the Typo3 backend after editing something using the modal dialog.
Multiple errors occur during navigation to a different page or Typo3 module because the ContentContainer variable is undefined.
I found the piece of code that is removing the ContentContainer in Resources/Public/JavaScript/Editor.js, Line 134.

What is the reason for deleting this variable? If i remove Line 134, and Lines 126-130 as well, the editor is seemingly working as intended.

We have multiple Typo3 installations that all exhibit this behavior.

**Comment by mabolek** [comment]
Hi Kevin!

Thank you for your bug report. I suspect the issue remains with version 1.9 (released yesterday).

I'm going to have someone look at this, especially like 134 in Editor.js. https://github.com/FriendsOfTYPO3/frontend_editing/blob/v1.8.3/Resources/Public/JavaScript/Editor.js#L134

**Comment by mabolek** [comment]
@codegm Maybe you have some input. I think the change in line 134 came from you as a resolution to a similar problem.

**Comment by codegm** [comment]
With the current v9 branch and master from frontend_editing i have no problems with the edit icon panel. And even when switching back to `delete top.TYPO3.Backend;` I can't reproduce the old error at the moment.

I also not know what kevin mean with;
> navigation built in to the Typo3 backend

and

> page or Typo3 module

in frontend context?

I'am not sure which object was undefined (Uncaught TypeError: Cannot read property 'attach' of undefined), but i decided back then, not remove the whole `top.TYPO3.Backend`, but remove only the `ContentContainer` because that was set some lines above and is recreatet each time the modal is used. The `delete top.TYPO3.Backend;` comes from commit 90323bbd5dc800ba3754bedd4d1600fc5bd5f5a7 

Sorry, that i can't really help...

**Comment by mabolek** [comment]
Thank you, @codegm.

**Comment by kevinandrewsde** [comment]
Hi guys,

> I also not know what kevin mean with;
> 
> > navigation built in to the Typo3 backend
> and
> 
> > page or Typo3 module
> 
> in frontend context?

I mean the normal navigation tree that is still visible when frontend editing is opened as an iframe in the Typo3 backend. I cant navigate to other modules, such as "Template" or other regular Pages anymore, as all Buttons cause errors. The navigation tree in the frontend editing iframe, on the other Hand, works fine.

> I'am not sure which object was undefined

TYPO3.Backend is undefined after the delete command is issued on closing the modal editing window
