### ISSUE TITLE
404 for jquery-ui-1.10.3.custom.min.css

### ISSUE THREAD

**Issue by webian** [FriendsOfTYPO3/frontend_editing#440]
This:
https://github.com/FriendsOfTYPO3/frontend_editing/blob/7941623d54c1df30d5096b58aa32e90663e844d8/Resources/Private/Layouts/DocHeader.html#L3
renders as `http://domain.ext/typo3conf/ext/frontend_editing/Resources/Public/EXT:viewpage/Resources/Public/Css/ui-lightness/jquery-ui-1.10.3.custom.min.css` so it's 404.

Is this css needed?

**Comment by pxamike** [comment]
So this issue is only in the develop-2.0 -branch. I can't say for sure with regards to viewpage (from where it stems) but in frontend_editing it looks like only jquery-ui resizable ( https://jqueryui.com/resizable/ ) is used. From what I can tell by going on actually used css in viewpage, ui-resizable sets "position: relative;", something backend.css already sets.
![ksnip_20201104-151822](https://user-images.githubusercontent.com/12510409/98124482-89836100-1eb3-11eb-80ef-d1dae2aeea89.png)

Strictly speaking it may not be needed but since ui-resizable is used and the css-file will be cached as viewpage uses it, I think it make sense to fix the inclusion rather than removing it.

**Comment by mabolek** [comment]
@MattiasNilsson Sounds like we should think carefully about whether to include this or not.

**Comment by MattiasNilsson** [comment]
@mabolek I will put it on my list of stuff to check!
