### ISSUE TITLE
Breaks PhotoSwipe in bootstrap_package

### ISSUE THREAD

**Issue by abvdveen** [FriendsOfTYPO3/frontend_editing#484]
If you enable frontend editing and visit a page with for example an 'image' CE with PhotoSwipe plugin, you get a js error in console: Syntax error, unrecognized expression: #&gid=lightbox-group-89&pid=0 and are unable to view the images with the PhotoSwipe carousel.

**Comment by Messj1** [comment]
@abvdveen we need more information on this.

1. We need the information about the installed plugins and version. There are plenty of bootstrap_package extensions.
I guess you have following package installed: `bk2k/bootstrap-package`
2. It is indeed nice to have more information about the steps which produced the problem.
I guess u were logged in and have also the capability to edit in frontend.?
4. The HTML snippet of the anchor element would be nice.
I guess it is the anchor because your posted message shows something similarly to a hash part of an URL.
3. Last but not least a clear error message would be nice.
So you mean, you are unable to open images with lightbox, have always exactly one error message on startup? in your console `Syntax error, unrecognized expression: #&gid=lightbox-group-89&pid=0 `, you were unable to open lightbox. But the rest was working. An there was no stack trace or file name  or another message in the console?

**Comment by abvdveen** [comment]
@Messj1 I was in the process of creating a BE account for you, so you could check things out on my dev site. However, when switching to that account, I didn't get the error anymore. Subsequently I also didn't get the error when switching back to the admin, or other BE accounts. I'm tempted to ascribe it to a caching issue. Which seems strange, as caches are cleared regularly, either when updating ext (for instance frontend_editing from 1.9.7 to 1.9.9), or manually in the BE. Is there a cache that may not have been cleared, and is used by frontend_editing?

Perhaps it's best not to put your valuable time and effort in this and for now close this issue. I will also comment on #473, which was closed and where I commented it wasn't fixed: this seems to be working also, after I created the new BE testaccount.

**Comment by MattiasNilsson** [comment]
@abvdveen I get it but report it if this happens again :)
