### ISSUE TITLE
Cancel operations do no close the Modal in v2

### ISSUE THREAD

**Issue by MattiasNilsson** [FriendsOfTYPO3/frontend_editing#503]
Cancel operations do no close the Modal in v2 and it still kept open during backend.

<img width="1473" alt="Screenshot 2021-03-21 at 19 12 15" src="https://user-images.githubusercontent.com/1718315/111916088-90cd9480-8a79-11eb-9357-a4d5acb55353.png">

**Comment by MattiasNilsson** [comment]
@Messj1 Maybe this is something you can take a look at? It is for develop-2.0 branch.

**Comment by Messj1** [comment]
@MattiasNilsson `TYPO3/CMS/FrontendEditing/Modal.dismissModal` doesn't work as it should. Since the `dismissModal` get called by button click in general the problem is related to #504 and vice versa.

The problem seems to be that the jqueryElement generated by `$(this)` won't trigger the events. The HTML Fragment is the same as in `TYPO3/CMS/Backend/Modal.currentModal`, but the jqueryElements are not equal (respectively the data)  ...  :thinking:

Solved by a TODO statement :shushing_face:
